version: 2
updates:
  - package-ecosystem: docker
    directory: /node22
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: node
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /python312
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: python
        update-types:
          - version-update:semver-minor
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /python314
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: python
        update-types:
          - version-update:semver-minor
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /java21
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: eclipse-temurin
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /java25
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: eclipse-temurin
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 2
