#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "Usage: $0 <source-revision> <release-record-directory> <manifest-path>" >&2
  exit 2
fi

source_revision="$1"
record_directory="$2"
manifest_path="$3"
profiles=(node22 python312 python314 java21 java25)

if [[ ! "$source_revision" =~ ^[0-9a-f]{40}$ ]]; then
  echo "Invalid source revision: ${source_revision}" >&2
  exit 1
fi

declare -A images contract_tags commit_tags digests runtime_versions base_digests logical_sizes

for expected_profile in "${profiles[@]}"; do
  record="${record_directory}/${expected_profile}.record"
  if [[ ! -s "$record" ]]; then
    echo "Release record is missing or empty: ${record}" >&2
    exit 1
  fi

  profile=
  image=
  contract_tag=
  commit_tag=
  digest=
  runtime_version=
  base_digest=
  logical_size_bytes=
  # Records are generated by this workflow from release-image.sh outputs.
  # shellcheck disable=SC1090
  source "$record"

  for required_name in profile image contract_tag commit_tag digest runtime_version base_digest logical_size_bytes; do
    if [[ -z "${!required_name:-}" ]]; then
      echo "Required release value is missing from ${record}: ${required_name}" >&2
      exit 1
    fi
  done

  if [[ "$profile" != "$expected_profile" ]]; then
    echo "Release profile mismatch: expected ${expected_profile}, got ${profile}" >&2
    exit 1
  fi

  expected_image="ghcr.io/experto-hub/ci-${profile}"
  if [[ "$image" != "$expected_image" ]]; then
    echo "Release image mismatch for ${profile}: expected ${expected_image}, got ${image}" >&2
    exit 1
  fi

  if [[ "$contract_tag" != "1" ]]; then
    echo "Invalid contract tag for ${profile}: ${contract_tag}" >&2
    exit 1
  fi

  if [[ "$commit_tag" != "sha-${source_revision}" ]]; then
    echo "Invalid commit tag for ${profile}: ${commit_tag}" >&2
    exit 1
  fi

  if [[ ! "$digest" =~ ^sha256:[0-9a-f]{64}$ ]]; then
    echo "Invalid registry digest for ${profile}: ${digest}" >&2
    exit 1
  fi

  if [[ ! "$base_digest" =~ ^sha256:[0-9a-f]{64}$ ]]; then
    echo "Invalid base digest for ${profile}: ${base_digest}" >&2
    exit 1
  fi

  if [[ ! "$runtime_version" =~ ^[0-9][0-9A-Za-z._+-]*$ ]]; then
    echo "Invalid runtime version for ${profile}: ${runtime_version}" >&2
    exit 1
  fi

  if [[ ! "$logical_size_bytes" =~ ^[0-9]+$ ]]; then
    echo "Invalid logical image size for ${profile}: ${logical_size_bytes}" >&2
    exit 1
  fi

  images[$profile]="$image"
  contract_tags[$profile]="$contract_tag"
  commit_tags[$profile]="$commit_tag"
  digests[$profile]="$digest"
  runtime_versions[$profile]="$runtime_version"
  base_digests[$profile]="$base_digest"
  logical_sizes[$profile]="$logical_size_bytes"
done

mkdir -p "$(dirname "$manifest_path")"
{
  printf '{\n'
  printf '  "sourceRevision": "%s",\n' "$source_revision"
  printf '  "images": {\n'
  for index in "${!profiles[@]}"; do
    profile="${profiles[$index]}"
    printf '    "%s": {\n' "$profile"
    printf '      "image": "%s",\n' "${images[$profile]}"
    printf '      "contractTag": "%s",\n' "${contract_tags[$profile]}"
    printf '      "commitTag": "%s",\n' "${commit_tags[$profile]}"
    printf '      "digest": "%s",\n' "${digests[$profile]}"
    printf '      "runtimeVersion": "%s",\n' "${runtime_versions[$profile]}"
    printf '      "baseDigest": "%s",\n' "${base_digests[$profile]}"
    printf '      "logicalSizeBytes": %s\n' "${logical_sizes[$profile]}"
    if ((index == ${#profiles[@]} - 1)); then
      printf '    }\n'
    else
      printf '    },\n'
    fi
  done
  printf '  }\n'
  printf '}\n'
} > "$manifest_path"
test -s "$manifest_path"
echo "release_manifest=generated path=${manifest_path} profiles=${profiles[*]}"
